### Register a new user
POST http://localhost:7777/api/auth/register
Content-Type: application/json

{
  "name": "Juan Diego Lopez",
  "email": "juan@gmail.com",
  "phone": "+573185022214",
  "password": "1234"
}

### Login user
POST http://localhost:7777/api/auth/login
Content-Type: application/json

{
  "email": "juandiegolopez@outlook.com",
  "password": "1234"
}

### Logout user
POST http://localhost:7777/api/auth/logout

### Check session
GET  http://localhost:7777/api/auth/whoami
