### Get address from current logged user
GET http://localhost:7777/api/users/address


### Add address for current logged user
POST http://localhost:7777/api/users/address
Content-Type: application/json

{
  "name": "Home",
  "description": "456 Bourbon Street, Ingrid Complex, #504 New Orleans, LA, 09873",
  "lat": 70,
  "lng": -40
}