### Get address from current logged user
GET http://localhost:7777/api/users/address


### Add address for current logged user
POST http://localhost:7777/api/users/address
Content-Type: application/json

{
  "name": "Home",
  "description": "456 Bourbon Street, Ingrid Complex, #504 New Orleans, LA, 09873",
  "lat": 70,
  "lng": -40
}

### Delete address by id
DELETE http://localhost:7777/api/users/address/1

### Get payments from current logged user
GET http://localhost:7777/api/users/payment

### Add payment for current logged user
POST http://localhost:7777/api/users/payment
Content-Type: application/json

{
  "type": "credit",
  "bank": "Bancolombia",
  "number": "1111111111111111",
  "name": "JUAN LOPEZ",
  "expiration": "2024-01-01T05:00:00.000Z",
  "securityCode": 111
}

### Delete payment by id
DELETE http://localhost:7777/api/users/payment/1
